// lib/renderMarkdown.ts
export function generateMarkdownFromPlan(plan: PlanResponse | null): string {
    if (!plan) return "# No plan available";

    const { goal, why, tasks } = plan;

    return `
# Executive Summary
**Goal:** ${goal}
**Why:** ${why}

## Execution Roadmap
${tasks.map(t => `- **[${t.id}]** ${t.title} (\`${t.file}\`) - Priority: ${t.priority.toUpperCase()}`).join('\n')}

---
*Generated by Company OS Executive Engine*
`;
}
