// lib/renderMarkdown.ts
import { CreatePlanResponse } from "@/types/dto/create-plan.response";

export function generateMarkdownFromPlan(plan: CreatePlanResponse | null): string {
    if (!plan) return "# No plan available";

    const { goal, why, dag } = plan;

    return `
# Executive Summary
**Goal:** ${goal}
**Why:** ${why}

## Execution Roadmap
${dag.map(t => `- **[${t.id}]** ${t.title} (\`${t.file}\`) - Priority: ${t.priority.toUpperCase()}`).join('\n')}

---
*Generated by Company OS Executive Engine*
`;
}
