export enum ErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",

  // Resources
  NOT_FOUND = "NOT_FOUND",
  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",

  // Domain
  INVALID_PLAN = "INVALID_PLAN",
  INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION",

  // Infrastructure
  DATABASE_ERROR = "DATABASE_ERROR",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",

}